# SonarQube Project Key
sonar.projectKey=TTT-Frontend-Github

# Define the source directories for SonarQube analysis
sonar.sources=.

# Include the lcov.info file for coverage reporting
sonar.javascript.lcov.reportPaths=coverage/lcov.info
