export const PERMISSIONS = {
  DASHBOARD: "Dashboard",
  ROLES_PERMISSIONS: {
    MAIN: "Roles & Permissions",
    CREATE: "Create Role",
    EDIT: "Edit Role",
    LIST: "Role List",
    DELETE: "Delete Role",
  },
  USER_MANAGEMENT: {
    MAIN: "User Management",
    CREATE: "Create User",
    EDIT: "Edit User",
    LIST: "User List",
    DELETE: "Delete User",
    SUSPEND_ACTIVATE: "Suspend/Activate User Accounts",
    APPROVE_REJECT: "Approve/Reject New Member Requests",
    RESEND_INVITATION: "Resend Invitation",
  },
  SUBSCRIPTION_PLANS: {
    MAIN: "Subscription Plans",
    CREATE: "Create Subscription",
    EDIT: "Edit Subscription",
    LIST: "Subscription List",
    DELETE: "Delete Subscription",
    MANAGE_PAYMENTS: "Manage Payments and Invoices",
    PROCESS_REFUNDS: "Process Refunds",
    SUSPEND_ACTIVATE: "Suspend/Activate User Subscriptions",
    PUBLISH_SUBSCRIPTIONS: "Publish Subscriptions",
  },
  COMMUNITY_MANAGEMENT: {
    MAIN: "Manage Community",
    CREATE: "Create Community",
    EDIT: "Edit Community",
    LIST: "Community List",
    DELETE: "Delete Community",
    MODERATE_COMMENTS: "Moderate Comments and Posts",
    REPORTED_COMMENTS: "Reported Comments",
    BLOCKED: "Blocked Community",
    UNBLOCK: "Unblock Community",
    PUBLIC_COMMUNITY_ACCESS:"Public community access",
  },
  CONTENT_MANAGEMENT: {
    MAIN: "Manage Content",
    CREATE: "Create Content",
    EDIT: "Edit Uploaded Content",
    LIST: "Content List",
    BLOCKED: "Blocked Content",
    DELETE: "Delete Content",
    UNBLOCK: "Unblock Contents",
    REPORT_FLAG: "Report/Flag Inappropriate Content",
    PUBLISH_CONTENT: "Publish Content",
    SUSPEND_ACTIVATE_CONTENT: "Suspend/Activate Content",
    CONTENT_CREATOR_PROFILE:"Creator Profile"
  },
  NOTIFICATION_MANAGEMENT: {
    MAIN: "Notification Management",
    CREATE: "Create Notifications (Email, Push, SMS)",
    EDIT_TEMPLATES: "Edit Notification Templates",
    VIEW_LOGS: "View Notification Logs",
    SCHEDULE: "Schedule Notifications",
    DELETE: "Delete Notifications",
  },
  PERMISSION_MANAGEMENT: {
    MAIN: "Permission Management",
    CREATE: "Create Permissions",
    EDIT: "Edit Permissions",
    LIST: "View Permissions List",
    ASSIGN_TO_ROLES: "Assign Permissions to Roles",
  },
  ORGANIZATIONS: {
    MAIN: "Organizations",
    CREATE: "Create Organization",
    EDIT: "Edit Organization Details",
    LIST: "Organization List",
    REMOVE: "Remove Organizations",
    MANAGE_CONTENT: "Manage Organization-Specific Content",
    APPROVE_REJECT_REQUESTS: "Approve/Reject Organization Requests",
    SUSPEND_ACTIVATE: "Suspend/Activate Organization",
  },
  CATEGORY_MANAGEMENT: {
    MAIN: "Category Management",
    ADD_NEW: "Add New Categories (for Content)",
    EDIT: "Edit Category Details",
    LIST: "View Category Lists",
    DELETE: "Delete Categories",
  },
  ANALYTICS_REPORTS: {
    VIEW_USER_ACTIVITY: "View User Activity Reports",
    GENERATE_REVENUE_REPORTS: "Generate Subscription Revenue Reports",
    ANALYZE_CONTENT: "Analyze Content Performance",
    TRACK_ENGAGEMENT: "Track Community Engagement Metrics",
    EXPORT_DATA: "Export Data for Analysis",
  },
  ACCESS_CONTROL: {
    RESTRICT_CONTENT: "Restrict Access to Specific Content",
    DEFINE_ACCESS_LEVELS: "Define Access Levels for Content and Features",
    ENABLE_DISABLE_FEATURES: "Enable/Disable Features for Specific Role",
  },
  RESOURCE_AND_RESEARCH: {
    MAIN: "Resource and Research",
    NEW: "New",
    POPULAR: "Popular",
    PRESONALISED: "Personalised",
    CONTINUE_WATCHING: "Continue Watching",
  },
  COMMUNITY_TABLE: {
    MAIN: "Community Table",
  },
  BINS: {
    MAIN: "Bins",
    RECENTS: "Recents",
    SHARED_WITH_ME: "Shared with me",
    MY_BIN: "My Bin",
  },
  CHATS: {
    MAIN: "Chats",
  },
  MY_PROFILE: {
    MAIN: "Personal info",
  },
  CHAT_MANAGEMENT: {
    MAIN: "Manage Chat",
    CREATE_CHANNEL: "Create Channel",
    EDIT_CHANNEL: "Edit Channel",
    LIST_CHANNEL: "Channel List",
    BLOCKED_CHANNEL: "Blocked Channel",
    DELETE_CHANNEL: "Delete Channel",
    UNBLOCK_CHANNEL: "Unblock Channel",
    // CREATE_GROUP: "Create Group",
    // EDIT_GROUP: "Edit Group",
    // LIST_GROUP: "Group List",
    // DELETE_GROUP: "Delete Group",
  },
};
