export const URL_CONSTANTS = {
  USER_DASHBORAD: "/",
  LOGIN: "/auth/login",
  SIGNUP:"/auth/signup",
  FORGOT_PASSWORD: "/auth/forgot-password",
  RESET_PASSWORD: "/auth/reset-password",
  JOIN_INVITATION: "/auth/join-invitation",
  CONTACT_SALES:"/auth/contact-sales",
  ADMIN_DASHBORAD: "/admin",

  ADMIN_SUBSCRIPTION_MANAGEMENT_CREATE: "/admin/subscription-management/create",
  ADMIN_SUBSCRIPTION_MANAGEMENT_VIEW: "/admin/subscription-management/view",
  ADMIN_SUBSCRIPTION_MANAGEMENT_EDIT: (id: number) => `/admin/subscription-management/edit/${id}`,

  ADMIN_COMMUNITY_LIST: "/admin/community/view",
  ADMIN_COMMUNITY_CREATION: "/admin/community/create",
  ADMIN_COMMUNITY_EDIT: (id: number) => `/admin/community/edit/${id}`,
  ADMIN_COMMUNITY_REPORTED_COMMENTS: "/admin/community/reported-comments",

  ADMIN_ORGANISATION_MANAGEMENT_CREATE: "/admin/organisation-management/create",
  ADMIN_ORGANISATION_MANAGEMENT_NEW: "/admin/organisation-management",
  ADMIN_ORGANISATION_MANAGEMENT_VIEW: "/admin/organisation-management/view",
  ADMIN_ORGANISATION_MANAGEMENT_EDIT: (id: number) => `/admin/organisation-management/edit/${id}`,

  ADMIN_CONTENT_LIST: "/admin/content/view",
  ADMIN_CONTENT_CREATION: "/admin/content/create",
  ADMIN_CONTENT_CREATOR_PROFILE: "/admin/content/content-creator",
  ADMIN_CONTENT_BLOCK: "/admin/content/blocked",
  ADMIN_CONTENT_EDIT: (id: string) => `/admin/content/edit/${id}`,
  ADMIN_CONTENT_PRIVIEW: (id: string) => `/admin/content/preview/${id}?preview=true`,

  ADMIN_ROLE_MANAGEMENT_CREATE: "/admin/role-management/create",
  ADMIN_ROLE_MANAGEMENT_EDIT: (id: number) => `/admin/role-management/edit/${id}`,
  ADMIN_ROLE_MANAGEMENT_VIEW: "/admin/role-management/view",

  ADMIN_USER_MANAGEMENT_CREATE_USER: "/admin/user-management/create",
  ADMIN_USER_MANAGEMENT_EDIT_USER: (id: number) => `/admin/user-management/edit-user/${id}`,
  ADMIN_USER_MANAGEMENT_PREVIEW_CONTENT_CREATOR: (id: number) => `/admin/user-management/preview-content-creator/${id}`,
  ADMIN_USER_MANAGEMENT_VIEW_USER: "/admin/user-management/users",

  ADMIN_CHAT_MANAGEMENT: "/admin/chats",
  ADMIN_CHAT_MANAGEMENT_VIEW_CHANNEL: "/admin/chats/channel/view",
  ADMIN_CHAT_MANAGEMENT_CREATE_CHANNEL: "/admin/chats/channel/create",
  ADMIN_CHAT_MANAGEMENT_EDIT_CHANNEL: (id: number) => `/admin/chats/channel/edit/${id}`,
  ADMIN_CHAT_MANAGEMENT_BLOCKED_CHANNEL: "/admin/chats/channel/blocked",
  ADMIN_CHAT_MANAGEMENT_VIEW_GROUP: "/admin/chats/group/view",
  ADMIN_CHAT_MANAGEMENT_VIEW_GROUP_ACTION: (id?: number, created_by?: string, group_name?: string) => `/admin/chats/group/view/${id}?createdBy=${created_by}&title=${group_name}`,
  ADMIN_CHAT_MANAGEMENT_CREATE_GROUP: "/admin/chats/group/create",
  ADMIN_COMMUNITY_BLOCK: "/admin/community/blocked",

  BINS: "/bins",
  RESOURCE_AND_RESEARCH: "/resource-and-research",
  COMMUNITY_TABLE: "/community-table",
  COMMUNITY_TABLE_DISTRICT: "/community-table/district",
  DASHBORAD: "/dashboard",
  MY_PROFILE: "/personal-info",
  NOTIFICATIONS: "/personal-info/notifications",
  CHATS: "/chats",
  CONTENT_CREATOR_PROFILE_FOR_EDUCATOR: "/resource-and-research/creator",
  RESOURCE_AND_RESEARCH_PRIVIEW: (id: string) => `/content-details/${id}`,


  FOOTER_ABOUT: "/about-us",
  FOOTER_FAQS: "/#faq-section",
  FOOTER_REVIEWS: "/reviews",
  FOOTER_BLOGS: "/blogs",
  FOOTER_PODCAST: "/podcast",
  FOOTER_CAREERS: "/careers",
  FOOTER_HELP_CENTER: "/help-center",
  FOOTER_TERM_OF_USE: "/terms",
  FOOTER_PRIVACY_POLICY: "/privacy-policy",
  FOOTER_COOKIE_POLICY: "/cookie-policy",

  SUPPORT_URL: "/support",
  MANAGE_MEMBERS: "/chats/manage-members",
};
