import { GetRoleDetailsProps } from "@/types/roleAndPermission";
import {
  genericQueryBuilder,
  genericQueryMutation,
} from "./middleware/genericBuilder";
import { mainEndPointCreator } from "./middleware/mainEndPointCreator";
import {
  DeleteRoleResponseProps,
  LoginResponseType,
  ForgotPasswordResType,
  ResetPasswordResType,
  AcceptInvitationResType,
  CreateUserResType,
  UpdateUserResType,
  GetSingleUserResType,
  UpdateUserStatusResType,
  LikeForumResType,
  ReportCommentResType,
  LikeCommentResType,
  GetOnboardingQnasResType,
  ReportReportResType,
  PostCommunityCommentResType,
} from "@/types/reducer";
import { UserDetailsResponse } from "@/types/userManagementType";
import {
  CategoryListResponse,
  GetSingleForumResponseData,
} from "@/types/community";
import { CreateUserType } from "@/types/signupType";
import { OrganisationListProps } from "@/types/organisation";
import {
  CommentsResType,
  GetSingleForumDetailsResType,
  RelatedTopicsRes,
  ReplyResType,
} from "@/types/community/CommunityDetails";
import {
  DeleteReporetedCommentsRes,
  IgnoreReporetedCommentsRes,
  ReportedCommentRes,
} from "@/types/community/ReportedCommentsType";
import { CreateBinRes, GetBinsRes, GetContentFromBinRes, GetSingleBinRes, SharedBinRes, UpdateBinRes } from "@/types/bins/binsType";
import { BlockedChannelListResType, ChannelListResType, CreateChannelResType, GetAllGroupRes, SingleChannelResType } from "@/types/chatAdminTypes";
import {
  GlobalSearchResultProps,
  IndividualContentListResponseProps,
  LikeContentResponseProps,
  RelatedContentResponseProps,
} from "@/types/content";
import { GlobalUsersListReponse } from "@/types/user";
import { contentCreatorContentDataResType, contentCreatorDataAdminSide } from "@/types/contentCreatorProfile";
import { AddMembersToGroupProps, CreateGroupResponseProps, DeleteGroupResponseProps, SendMessageProps } from "@/types/chats";
import { NotificationListResponseProps } from "@/types/notifications";
import { BlockedCommunityListResType } from "@/types/community/BlockedCommunityType";

export default function allReducer(builders: any) {
  return {
    getRoles: genericQueryBuilder(builders),
    createRole: genericQueryMutation(builders),
    getUsers: genericQueryBuilder<UserDetailsResponse>(builders),
    updateUserStatus: genericQueryMutation<UpdateUserStatusResType>(builders),
    createUser: genericQueryMutation<CreateUserType>(builders),
    getPermissions: genericQueryBuilder(builders),
    getSingleUser: genericQueryBuilder<GetSingleUserResType>(builders),
    login: genericQueryMutation<LoginResponseType>(builders),
    forgotPassword: genericQueryMutation<ForgotPasswordResType>(builders),
    deleteRole: genericQueryMutation<DeleteRoleResponseProps>(builders),
    getRoleByRoleId: genericQueryBuilder<GetRoleDetailsProps>(builders),
    createSubscriptionPlan: genericQueryMutation(builders),
    getSubscriptionPlanList: genericQueryBuilder(builders),
    updateUser: genericQueryMutation<UpdateUserResType>(builders),
    getOrganisationList: genericQueryBuilder<OrganisationListProps>(builders),
    createCommunity: genericQueryMutation(builders),
    editCommunity: genericQueryMutation(builders),
    getForum: genericQueryBuilder<GetSingleForumResponseData>(builders),
    editRole: genericQueryMutation(builders),
    resetPassword: genericQueryMutation<ResetPasswordResType>(builders),
    sendInvitationLink: genericQueryMutation(builders),
    createUserAndSendInvitation:
      genericQueryMutation<CreateUserResType>(builders),
    acceptInvitation: genericQueryMutation<AcceptInvitationResType>(builders),
    deleteFourm: genericQueryMutation<any>(builders),
    getCategory: genericQueryBuilder<CategoryListResponse>(builders),
    deleteSubscriptionPlan: genericQueryMutation(builders),
    getSubscriptionPlanById: genericQueryBuilder(builders),
    editSubscriptionPlan: genericQueryMutation(builders),
    changeSubscriptionPlanStatus: genericQueryMutation(builders),
    publishSubscriptionPlan: genericQueryMutation(builders),
    getContentList: genericQueryBuilder(builders),
    updateContentStatus: genericQueryMutation(builders),
    createOrganisation: genericQueryMutation(builders),
    likeForum: genericQueryMutation<LikeForumResType>(builders),
    getOnboardingQnas: genericQueryBuilder<GetOnboardingQnasResType>(builders),
    addOnboardingQnas: genericQueryMutation(builders),
    createContent: genericQueryMutation(builders),
    editContent: genericQueryMutation(builders),
    getContentById: genericQueryBuilder(builders),
    getOrganisationDetailsById: genericQueryBuilder(builders),
    updateOrganisation: genericQueryMutation(builders),
    getCommunityCommentsList: genericQueryBuilder<CommentsResType>(builders),
    postCommunityComment:
      genericQueryMutation<PostCommunityCommentResType>(builders),
    postCommunityCommentReply:
      genericQueryMutation<PostCommunityCommentResType>(builders),
    getCommunityRepliesList: genericQueryBuilder<ReplyResType>(builders),
    likeCommentById: genericQueryMutation<LikeCommentResType>(builders),
    reportComment: genericQueryMutation<ReportCommentResType>(builders),
    blockContent: genericQueryMutation(builders),
    getBlockedContentList: genericQueryBuilder(builders),
    unblockContent: genericQueryMutation(builders),
    getSingleForumDetails:
      genericQueryBuilder<GetSingleForumDetailsResType>(builders),
    deleteContent: genericQueryMutation(builders),
    getReportReasons: genericQueryBuilder<ReportReportResType>(builders),
    getReportedCommentsList: genericQueryBuilder<ReportedCommentRes>(builders),
    deleteReportedComments:
      genericQueryMutation<DeleteReporetedCommentsRes>(builders),
    ignoreReportedComments:
      genericQueryMutation<IgnoreReporetedCommentsRes>(builders),
    getRelatedCommunityTopics: genericQueryBuilder<RelatedTopicsRes>(builders),
    getContentGlobalList: genericQueryBuilder(builders),
    getIndividualContentList:
      genericQueryBuilder<IndividualContentListResponseProps>(builders),
    likeContent: genericQueryMutation<LikeContentResponseProps>(builders),
    resourceAndResearchGlobalSearch:
      genericQueryBuilder<GlobalSearchResultProps>(builders),
    getRelatedContent:
      genericQueryBuilder<RelatedContentResponseProps>(builders),
    viewContent: genericQueryMutation(builders),
    updateWatchDuration: genericQueryMutation(builders),
    resendUserInvitation: genericQueryMutation(builders),
    getBins: genericQueryBuilder<GetBinsRes>(builders),
    createNewBin: genericQueryMutation<CreateBinRes>(builders),
    getSingleBin: genericQueryBuilder<GetSingleBinRes>(builders),
    updateBin: genericQueryMutation<UpdateBinRes>(builders),
    deleteBin: genericQueryMutation(builders),
    saveContentToBin: genericQueryMutation(builders),
    getContentFromBin: genericQueryBuilder<GetContentFromBinRes>(builders),
    sendMessage: genericQueryMutation<SendMessageProps>(builders),
    removeContentFromBin: genericQueryMutation(builders),
    getGlobalUsersList: genericQueryBuilder<GlobalUsersListReponse>(builders),
    createGroup: genericQueryMutation<CreateGroupResponseProps>(builders),
    searchGlobalChatDetails: genericQueryBuilder(builders),
    forumActivateDeactivate: genericQueryMutation<{ message: string }>(
      builders,
    ),
    contactSales: genericQueryMutation(builders),
    getChatHistory: genericQueryBuilder(builders),
    getGlobalChatHistory: genericQueryBuilder(builders),
    getGroupDetailsById: genericQueryBuilder(builders),
    addMembersToGroup: genericQueryMutation<AddMembersToGroupProps>(builders),
    getProfileByToken: genericQueryBuilder(builders),
    getOnboardingAnswersByToken: genericQueryBuilder(builders),
    updateProfileInfo: genericQueryMutation(builders),
    createChannel: genericQueryMutation<CreateChannelResType>(builders),
    getChannelList: genericQueryBuilder<ChannelListResType>(builders),
    deleteChannel: genericQueryMutation<{message: string;}>(builders),
    getSingleChannel: genericQueryBuilder<SingleChannelResType>(builders),
    updateChannel: genericQueryMutation<{message: string;}>(builders),
    blockChannel: genericQueryMutation<{message: string}>(builders),
    getBlockedChannel: genericQueryBuilder<BlockedChannelListResType>(builders),
    unblockChannel: genericQueryMutation(builders),
    shareBinWithUsers: genericQueryMutation(builders),
    getSharedBins: genericQueryBuilder<SharedBinRes>(builders),
    removeSharedBins: genericQueryMutation(builders),
    updatePassword: genericQueryMutation(builders),
    deleteAccount: genericQueryMutation(builders),
    deleteGroup: genericQueryMutation<DeleteGroupResponseProps>(builders),
    clearGroupChat: genericQueryMutation(builders),
    deleteMessage: genericQueryMutation(builders),
    getAllGroupList: genericQueryBuilder<GetAllGroupRes>(builders),
    getNotificationList: genericQueryBuilder<NotificationListResponseProps>(builders),
    updateGroupDetails: genericQueryMutation<{message: string}>(builders),
    createUpdateContentCreatorProfile: genericQueryMutation<{message: string}>(builders),
    getContentCreatorProfileForAdmin: genericQueryBuilder<contentCreatorDataAdminSide>(builders),
    deleteContentCreatorProfile: genericQueryMutation<{message: string;}>(builders),
    getContentCreatorProfileForEducator: genericQueryBuilder<contentCreatorDataAdminSide>(builders),
    getContentCreatorData: genericQueryBuilder<contentCreatorContentDataResType>(builders),
    checkContentCreatorProfile: genericQueryBuilder<{is_creator_created: boolean;}>(builders),
    deleteNotification: genericQueryMutation(builders),
    markNotificationAsRead: genericQueryMutation(builders),
    blockForumCommunity: genericQueryMutation<{message: string;}>(builders),
    getBlockedCommunityList: genericQueryBuilder<BlockedCommunityListResType>(builders),
    unblockCommunityForum: genericQueryMutation(builders),
    subscriberNewsletter: genericQueryMutation(builders),
    getCreatorProfilePublickList: genericQueryBuilder(builders),

  };
}

export const {
  useLazyGetRolesQuery,
  useCreateRoleMutation,
  useLazyGetUsersQuery,
  useUpdateUserStatusMutation,
  useCreateUserMutation,
  useLazyGetPermissionsQuery,
  useLazyGetSingleUserQuery,
  useLoginMutation,
  useForgotPasswordMutation,
  useDeleteRoleMutation,
  useLazyGetRoleByRoleIdQuery,
  useCreateSubscriptionPlanMutation,
  useLazyGetSubscriptionPlanListQuery,
  useLazyGetOrganisationListQuery,
  useLazyGetForumQuery,
  useCreateCommunityMutation,
  useEditCommunityMutation,
  useEditRoleMutation,
  useUpdateUserMutation,
  useResetPasswordMutation,
  useSendInvitationLinkMutation,
  useLazyGetCategoryQuery,
  useCreateUserAndSendInvitationMutation,
  useAcceptInvitationMutation,
  useDeleteSubscriptionPlanMutation,
  useLazyGetSubscriptionPlanByIdQuery,
  useEditSubscriptionPlanMutation,
  useChangeSubscriptionPlanStatusMutation,
  usePublishSubscriptionPlanMutation,
  useLazyGetContentListQuery,
  useUpdateContentStatusMutation,
  useDeleteFourmMutation,
  useCreateOrganisationMutation,
  useLikeForumMutation,
  useLazyGetOnboardingQnasQuery,
  useAddOnboardingQnasMutation,
  useCreateContentMutation,
  useEditContentMutation,
  useLazyGetContentByIdQuery,
  useLazyGetOrganisationDetailsByIdQuery,
  useUpdateOrganisationMutation,
  useLazyGetCommunityCommentsListQuery,
  usePostCommunityCommentMutation,
  usePostCommunityCommentReplyMutation,
  useLazyGetCommunityRepliesListQuery,
  useLikeCommentByIdMutation,
  useReportCommentMutation,
  useBlockContentMutation,
  useLazyGetBlockedContentListQuery,
  useUnblockContentMutation,
  useLazyGetSingleForumDetailsQuery,
  useDeleteContentMutation,
  useLazyGetReportReasonsQuery,
  useLazyGetReportedCommentsListQuery,
  useDeleteReportedCommentsMutation,
  useIgnoreReportedCommentsMutation,
  useLazyGetRelatedCommunityTopicsQuery,
  useLazyGetContentGlobalListQuery,
  useLazyGetIndividualContentListQuery,
  useLikeContentMutation,
  useLazyResourceAndResearchGlobalSearchQuery,
  useLazyGetRelatedContentQuery,
  useViewContentMutation,
  useUpdateWatchDurationMutation,
  useResendUserInvitationMutation,
  useLazyGetBinsQuery,
  useCreateNewBinMutation,
  useLazyGetSingleBinQuery,
  useUpdateBinMutation,
  useDeleteBinMutation,
  useSaveContentToBinMutation,
  useLazyGetContentFromBinQuery,
  useSendMessageMutation,
  useRemoveContentFromBinMutation,
  useLazyGetGlobalUsersListQuery,
  useCreateGroupMutation,
  useLazySearchGlobalChatDetailsQuery,
  useLazyGetChatHistoryQuery,
  useLazyGetGlobalChatHistoryQuery,
  useLazyGetGroupDetailsByIdQuery,
  useAddMembersToGroupMutation,
  useLazyGetProfileByTokenQuery,
  useLazyGetOnboardingAnswersByTokenQuery,
  useUpdateProfileInfoMutation,
  useForumActivateDeactivateMutation,
  useContactSalesMutation,
  useCreateChannelMutation,
  useLazyGetChannelListQuery,
  useDeleteChannelMutation,
  useLazyGetSingleChannelQuery,
  useUpdateChannelMutation,
  useBlockChannelMutation,
  useLazyGetBlockedChannelQuery,
  useUnblockChannelMutation,
  useShareBinWithUsersMutation,
  useLazyGetSharedBinsQuery,
  useRemoveSharedBinsMutation,
  useUpdatePasswordMutation,
  useDeleteAccountMutation,
  useDeleteGroupMutation,
  useClearGroupChatMutation,
  useDeleteMessageMutation,
  useLazyGetAllGroupListQuery,
  useLazyGetNotificationListQuery,
  useUpdateGroupDetailsMutation,
  useCreateUpdateContentCreatorProfileMutation,
  useLazyGetContentCreatorProfileForAdminQuery,
  useDeleteContentCreatorProfileMutation,
  useLazyGetContentCreatorProfileForEducatorQuery,
  useLazyGetContentCreatorDataQuery,
  useLazyCheckContentCreatorProfileQuery,
  useDeleteNotificationMutation,
  useMarkNotificationAsReadMutation,
  useBlockForumCommunityMutation,
  useLazyGetBlockedCommunityListQuery,
  useUnblockCommunityForumMutation,
  useSubscriberNewsletterMutation,
  useLazyGetCreatorProfilePublickListQuery,
} = mainEndPointCreator;
